scripts/install: refactor

diff --git a/scripts/install/create_db b/scripts/install/create_db
--- a/scripts/install/create_db
+++ b/scripts/install/create_db
@@ -1,25 +1,33 @@
 #!/bin/sh
 
-if [ -z "$ADMIN_EMAIL" ]; then
-        echo 'ERROR: ADMIN_EMAIL not provided'
-        exit 1
+CONFIG="$1/create.sql"
+
+if [ ! -f "$CONFIG" ] || [ -n "$ADMIN_EMAIL" ] || [ -n "$ADMIN_USER" ] || [ -n "$ADMIN_PASS" ]; then
+	if [ -z "$ADMIN_EMAIL" ]; then
+		echo "[$1] ERROR: ADMIN_EMAIL not provided"
+		exit 1
+	fi
+
+	if [ -z "$ADMIN_USER" ]; then
+		echo "[$1] ERROR: ADMIN_USER not provided"
+		exit 1
+	fi
+
+	if [ -z "$ADMIN_PASS" ]; then
+		echo "[$1] ERROR: ADMIN_PASS not provided"
+		exit 1
+	fi
+
+	cp "config/mysql/create.sql" "$CONFIG"
+	sed -i "s;\${ADMIN_EMAIL};$ADMIN_EMAIL;g" "$CONFIG"
+	sed -i "s;\${ADMIN_USER};$ADMIN_USER;g" "$CONFIG"
+	sed -i "s;\${ADMIN_PASS};$ADMIN_PASS;g" "$CONFIG"
+else
+	echo "[$1] INFO: Leaving old config"
 fi
 
-if [ -z "$ADMIN_USER" ]; then
-        echo 'ERROR: ADMIN_USER not provided'
-        exit 1
-fi
-
-if [ -z "$ADMIN_PASS" ]; then
-        echo 'ERROR: ADMIN_PASS not provided'
-        exit 1
-fi
-
-tmp_sql="tmp.sql"
-cp "config/mysql/create.sql" "$tmp_sql"
-sed -i "s;\${ADMIN_EMAIL};$ADMIN_EMAIL;g" "$tmp_sql"
-sed -i "s;\${ADMIN_USER};$ADMIN_USER;g" "$tmp_sql"
-sed -i "s;\${ADMIN_PASS};$ADMIN_PASS;g" "$tmp_sql"
-
-sudo cat "$tmp_sql" | sudo mysql
-rm "$tmp_sql"
+cat > "$1/install" << EOF
+#!/bin/sh
+sudo cat "$CONFIG" | sudo mysql
+echo "[$1] INFO: done"
+EOF
diff --git a/scripts/install/mysql b/scripts/install/mysql
--- a/scripts/install/mysql
+++ b/scripts/install/mysql
@@ -1,37 +1,27 @@
 #!/bin/sh
 
-if [ -z "$PHP_PASS" ]; then
-        echo 'ERROR: PHP_PASS not provided'
-        exit 1
+CONFIG="$1/secure.sql"
+
+if [ ! -f "$CONFIG" ] || [ -n "$PHP_PASS" ]; then
+	if [ -z "$PHP_PASS" ]; then
+		echo "[$1] ERROR: PHP_PASS not provided"
+		exit 1
+	fi
+
+	cp config/mysql/secure.sql "$CONFIG"
+	sed -i "s;\${PHP_PASS};$PHP_PASS;g" "$CONFIG"
+
+else
+	echo "[$1] INFO: Leaving old config"
 fi
 
+cat > "$1/install" << EOF
+#!/bin/sh
 sudo apt-get update
 sudo apt-get install mysql-server -y
-
 sudo systemctl enable mysql
 sudo systemctl start mysql
 sudo systemctl status mysql --no-pager -l
-
-echo "Users:"
-sudo mysql -e "SELECT Host,User FROM mysql.user"
-
-echo "Databases:"
-sudo mysql -e "SHOW DATABASES"
-
-echo "Privileges:"
-sudo mysql -e "SELECT Host,User,Db,
-Select_priv AS SEL,
-Insert_priv AS INS,
-Update_priv AS UPD,
-Delete_priv AS DEL,
-Create_priv AS CRT,
-Drop_priv AS DRP,
-Grant_priv AS GRN
-FROM mysql.db"
-
-tmp_sql="tmp.sql"
-cp "config/mysql/secure.sql" "$tmp_sql"
-sed -i "s;\${PHP_PASS};$PHP_PASS;g" "$tmp_sql"
-
-sudo cat "$tmp_sql" | sudo mysql
-rm "$tmp_sql"
+sudo cat "$CONFIG" | sudo mysql
+echo "[$1] INFO: done"
+EOF
